server:
  port: 1111

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jcifu/ms-store/products-ms
          
eureka:
  client:
    service-url:
      defaultZone: https://localhost:1111/eureka